import { LegalPageShell } from "@/components/marketing/legal-page-shell";

export const metadata = { title: "Terms of Service — VeloBot" };

export default function TermsPage() {
  return (
    <LegalPageShell title="Terms of Service" updatedAt="[DATE]">
      <p>
        These Terms of Service (&ldquo;Terms&rdquo;) govern access to and use of VeloBot, a website chatbot platform that lets a
        business (&ldquo;you,&rdquo; &ldquo;Customer&rdquo;) train a support bot on its own content, embed it on a website, and route
        conversations to human agents. They are a contract between you and{" "}
        <strong>[YOUR COMPANY LEGAL NAME]</strong> (&ldquo;VeloBot,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;), a company registered at{" "}
        <strong>[ADDRESS]</strong>. By creating an account or embedding a VeloBot widget, you agree to these Terms.
      </p>

      <h2>1. The service</h2>
      <p>
        VeloBot provides: a dashboard for creating and configuring chatbots; a knowledge-base ingestion pipeline that crawls or
        accepts uploads of your own content; an AI chat runtime that answers your website visitors using that content; an
        embeddable widget; a live agent inbox for escalated conversations; optional integrations (&ldquo;Connections&rdquo; and
        &ldquo;Bot Actions&rdquo;) that let a bot or agent call your own external systems; and, on qualifying plans, a read-only
        Developer API for pulling your own bots and conversations into other systems.
      </p>

      <h2>2. Accounts and eligibility</h2>
      <p>
        You must provide accurate information when creating an account and are responsible for activity under it, including
        actions taken by teammates you invite. You must be legally able to enter a binding contract in your jurisdiction.
      </p>

      <h2>3. Your content and your responsibility for it</h2>
      <ul>
        <li>
          You represent that you have the right to submit any content you crawl, upload, or otherwise feed into a bot&apos;s
          knowledge base, and that doing so doesn&apos;t infringe anyone else&apos;s rights.
        </li>
        <li>
          Any custom instructions you write for a bot (system prompt additions, guardrail topics, canned replies, workflow
          rules) are your responsibility — we don&apos;t review them before they go live.
        </li>
        <li>
          If you enable the optional cookie/consent banner feature, configuring and displaying an adequate notice to your own
          website&apos;s visitors — consistent with the law in your and your visitors&apos; jurisdictions — is your
          responsibility, not ours; VeloBot provides the mechanism, not legal advice on what it must say.
        </li>
        <li>
          You&apos;re responsible for how your team uses agent tools (claiming conversations, quick actions, Bot Actions that
          call your own systems) and for any external API credentials you connect through Connections.
        </li>
      </ul>

      <h2>4. Acceptable use</h2>
      <p>You won&apos;t use VeloBot to:</p>
      <ul>
        <li>Train or configure a bot to deceive visitors about the fact that they&apos;re talking to an AI when asked directly.</li>
        <li>Collect sensitive personal data from visitors beyond what&apos;s reasonably necessary for support (e.g. don&apos;t repurpose the chat as a form for collecting government ID numbers, health information, or financial account details).</li>
        <li>Attempt to bypass plan limits, rate limits, or the Developer API&apos;s scope (read-only, your own org&apos;s data).</li>
        <li>Send unsolicited bulk messages, malware, or attempt to compromise the platform&apos;s security.</li>
        <li>Reverse-engineer the widget or platform beyond what&apos;s allowed by law.</li>
      </ul>

      <h2>5. Fees and billing</h2>
      <p>
        Paid plans are billed in advance (monthly or yearly) via Razorpay. Add-ons (extra agent seats, extra AI messages) are
        billed as configured at purchase. Fees are non-refundable except where required by law or stated otherwise. We may
        change plan pricing with notice before your next billing cycle; continuing to use a paid plan after a price change
        takes effect means you accept the new price. Failing to pay may result in suspended access after a grace period.
      </p>

      <h2>6. AI-generated responses</h2>
      <p>
        A bot&apos;s replies are generated by a third-party large language model based on the content you provided, and are
        provided &ldquo;as is.&rdquo; VeloBot does not guarantee accuracy, and neither VeloBot nor you should treat AI-generated
        sentiment, intent, or entity extraction as verified fact — it&apos;s a hint for your team, not a source of truth. You&apos;re
        responsible for reviewing bot behavior and disabling or correcting it (via guardrails, workflow rules, or human
        escalation) if it produces answers you don&apos;t want given on your behalf.
      </p>

      <h2>7. Intellectual property</h2>
      <p>
        You retain ownership of your content and configuration. We retain ownership of the VeloBot platform, widget, and
        underlying technology. We may use aggregated, de-identified usage data (not your visitors&apos; conversation content) to
        improve the service.
      </p>

      <h2>8. Suspension and termination</h2>
      <p>
        We may suspend or terminate an account for material breach of these Terms, non-payment, or activity that risks harm
        to the platform or other customers. You may cancel at any time from Billing; cancellation takes effect at the end of
        the current billing period.
      </p>

      <h2>9. Disclaimers and limitation of liability</h2>
      <p>
        The service is provided &ldquo;as is&rdquo; without warranties of any kind, express or implied. To the maximum extent
        permitted by law, VeloBot&apos;s total liability for any claim arising from these Terms or the service is limited to the
        amount you paid us in the twelve months before the claim, and we aren&apos;t liable for indirect, incidental, or
        consequential damages.
      </p>

      <h2>10. Governing law</h2>
      <p>These Terms are governed by the laws of <strong>[GOVERNING LAW / JURISDICTION]</strong>, without regard to conflict-of-law rules.</p>

      <h2>11. Changes to these Terms</h2>
      <p>
        We&apos;ll post updates here and, for material changes, notify account admins by email. Continued use after a change
        takes effect means you accept it.
      </p>

      <h2>12. Contact</h2>
      <p>
        Questions about these Terms: <strong>[SUPPORT EMAIL]</strong>.
      </p>
    </LegalPageShell>
  );
}
